---
title: "Softonic App Exploration"
author: "Refik Türkeli"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,include=FALSE}
library(Rsmp)
library(dplyr)
```

### Most downloaded apps by paltform

```{r,echo=FALSE,message=FALSE,warning=FALSE}
data_softonic_app() %>% 
  dplyr::group_by(platform) %>% 
  dplyr::summarise(votes = sum(votes), apps = n(),
                   download_count = sum(download_count)) %>% 
  dplyr::arrange(desc(download_count)) %>% 
  knitr::kable()
```

### Top apps category

```{r,echo=FALSE,message=FALSE,warning=FALSE}
data_softonic_app() %>% 
  dplyr::group_by(platform) %>% 
  desc_nulls_last("download_count") %>% 
  dplyr::mutate(row = row_number()) %>% 
  dplyr::filter(row <= 100) %>% 
  dplyr::group_by(platform, category) %>% 
  dplyr::summarise(votes = sum(votes), apps = n()) %>% 
  dplyr::arrange(desc(platform), desc(apps)) %>% 
  dplyr::mutate(row = row_number()) %>% 
  dplyr::filter(row <= 5) %>% 
  knitr::kable()
```

This table screams that multimedia and games are big on all platforms.

### Top apps sub category

```{r,echo=FALSE,message=FALSE,warning=FALSE}
data_softonic_app() %>% 
  dplyr::group_by(platform) %>% 
  desc_nulls_last("download_count") %>% 
  dplyr::mutate(row = row_number()) %>% 
  dplyr::filter(row <= 100) %>% 
  dplyr::group_by(platform, category, sub_category) %>% 
  dplyr::summarise(votes = sum(votes), apps = n()) %>% 
  dplyr::group_by(platform) %>% 
  dplyr::arrange(desc(apps)) %>% 
  dplyr::mutate(row = row_number()) %>% 
  dplyr::filter(row <= 5) %>% 
  knitr::kable()
```

<!-- Vignettes are long form documentation commonly included in packages. Because they are part of the distribution of the package, they need to be as compact as possible. The `html_vignette` output type provides a custom style sheet (and tweaks some options) to ensure that the resulting html is as small as possible. The `html_vignette` format: -->

<!-- - Never uses retina figures -->
<!-- - Has a smaller default figure size -->
<!-- - Uses a custom CSS stylesheet instead of the default Twitter Bootstrap style -->

<!-- ## Vignette Info -->

<!-- Note the various macros within the `vignette` section of the metadata block above. These are required in order to instruct R how to build the vignette. Note that you should change the `title` field and the `\VignetteIndexEntry` to match the title of your vignette. -->

<!-- ## Styles -->

<!-- The `html_vignette` template includes a basic CSS theme. To override this theme you can specify your own CSS in the document metadata as follows: -->

<!--     output:  -->
<!--       rmarkdown::html_vignette: -->
<!--         css: mystyles.css -->

<!-- ## Figures -->

<!-- The figure sizes have been customised so that you can easily put two images side-by-side.  -->

<!-- ```{r, fig.show='hold'} -->
<!-- plot(1:10) -->
<!-- plot(10:1) -->
<!-- ``` -->

<!-- You can enable figure captions by `fig_caption: yes` in YAML: -->

<!--     output: -->
<!--       rmarkdown::html_vignette: -->
<!--         fig_caption: yes -->

<!-- Then you can use the chunk option `fig.cap = "Your figure caption."` in **knitr**. -->

<!-- ## More Examples -->

<!-- You can write math expressions, e.g. $Y = X\beta + \epsilon$, footnotes^[A footnote here.], and tables, e.g. using `knitr::kable()`. -->

<!-- ```{r, echo=FALSE, results='asis'} -->
<!-- knitr::kable(head(mtcars, 10)) -->
<!-- ``` -->

<!-- Also a quote using `>`: -->

<!-- > "He who gives up [code] safety for [code] speed deserves neither." -->
<!-- ([via](https://twitter.com/hadleywickham/status/504368538874703872)) -->
