# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 19:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('logo_url', models.CharField(max_length=500)),
                ('article', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_url', models.CharField(max_length=500)),
                ('parent_url', models.CharField(max_length=500, null=True)),
                ('request_time', models.DateTimeField()),
                ('spider_name', models.CharField(max_length=500)),
                ('callback_function', models.CharField(max_length=500)),
                ('spider_load_time', models.DateTimeField()),
                ('item', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
